### ISSUE TITLE
 --fares-clean error (not sure if vital)

### ISSUE THREAD

**Issue by mshodge** [open-track/dtd2mysql#37]
Hi there,

Small error with ` --fares-clean`, producing the following error:

`Applied restriction dates
{ Error: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'trains.flow.direction' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at PromisePool.query (/usr/local/lib/node_modules/dtd2mysql/node_modules/mysql2/promise.js:344:20)
    at CleanFaresCommand.queryWithRetry (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/CleanFaresCommand.js:111:27)
    at CleanFaresCommand.queryWithRetry (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/CleanFaresCommand.js:118:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column \'trains.flow.direction\' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by',
  code: 'ER_WRONG_FIELD_WITH_GROUP',
  errno: 1055,
  sqlState: '42000',
  sqlMessage: 'Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column \'trains.flow.direction\' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by' }
Removed old and irrelevant fares data`

Regards,

Michael

**Comment by linusnorton** [comment]
see https://github.com/open-track/dtd2mysql/issues/36
